name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 2 * * *'  # nightly at 02:00 UTC for extended fuzz/bench
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.21.x', '1.22.x', '1.23.x' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Cache Go build and mod
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go }}-

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./... -v

      - name: Race
        run: go test ./... -race -v

      - name: Fuzz (smoke 10s)
        run: |
          go test -run=^$ -fuzz=FuzzTransformMap -fuzztime=10s ./...
          go test -run=^$ -fuzz=FuzzTransformForm -fuzztime=10s ./...
          go test -run=^$ -fuzz=FuzzTransformCSV -fuzztime=10s ./...

  fuzz-nightly:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Long fuzz (2m)
        run: |
          go test -run=^$ -fuzz=FuzzTransformMap -fuzztime=2m ./...
          go test -run=^$ -fuzz=FuzzTransformForm -fuzztime=2m ./...
          go test -run=^$ -fuzz=FuzzTransformCSV -fuzztime=2m ./...

  bench:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Run benchmarks
        run: |
          go test -bench . -benchtime=2s -run=^$ ./... | tee bench.txt
      - name: Upload bench results
        uses: actions/upload-artifact@v4
        with:
          name: bench-results
          path: bench.txt
